export const PROTON_UPDATE = 'PROTON_UPDATE';
export const PARTICLE_CREATED = 'PARTICLE_CREATED';
export const PARTICLE_UPDATE = 'PARTICLE_UPDATE';
export const PARTICLE_DEAD = 'PARTICLE_DEAD';
export const EMITTER_ADDED = 'EMITTER_ADDED';
export const EMITTER_REMOVED = 'EMITTER_REMOVED';
export const PROTON_UPDATE_AFTER = 'PROTON_UPDATE_AFTER';
