/**
 * Similar to a Set but with a find method.
 *
 * NOTE There is a potential bug with how this is being used by the GPURenderer.
 * Currently the particle.id is used as the "item", because it is always unique.
 * The potential here is that even though the particles are generated by a Pool,
 * we could potentially reach the max number of particles allowed by this list,
 * causing the error to be thrown.
 */
export class UniqueList {
  constructor(max = Infinity) {
    this.max = max;
    this.items = [];
  }

  add(item) {
    if (this.has(item)) {
      return;
    }

    if (this.items.length + 1 === this.max) {
      throw new Error('UniqueList max size exceeded');
    }

    this.items.push(item);
  }

  has(item) {
    return this.items.indexOf(item) > 0;
  }

  find(item) {
    return this.items.indexOf(item);
  }
}
