export const INTEGRATION_TYPE_EULER = 'EULER';
export const INTEGRATION_TYPE_RK2 = 'RUNGE_KUTTA_2';
export const INTEGRATION_TYPE_RK4 = 'RUNGE_KUTTA_4';
export const INTEGRATION_TYPE_VERLET = 'VERLET';
